apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o0f0brolh-nodejs 
  janus-idp.io/tekton: o0f0brolh-nodejs
  backstage.io/kubernetes-id: o0f0brolh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o0f0brolh-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  